apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-deployment
  labels:
    app: k8-container-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8-container-app
  template:
    metadata:
      labels:
        app: k8-container-app
    spec:
      containers:
      - name: container-1
        image: gcr.io/kuber-project-418102/container_1:latest
        ports:
          - containerPort: 6000
        volumeMounts:
          - name: shared-volume
            mountPath: /kazi_PV_dir
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: pvc-for-k8-container-app