apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-for-k8-container-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard