apiVersion: v1
kind: Service
metadata:
  name: container-1-service
spec:
  type: LoadBalancer
  selector:
    app: k8-container-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6000