apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-deployment-2
  labels:
    app: k8-container-app-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8-container-app-2
  template:
    metadata:
      labels:
        app: k8-container-app-2
    spec:
      containers:
      - name: container-2
        image: gcr.io/kuber-project-418102/container_2:latest
        ports:
          - containerPort: 8000
        volumeMounts:
          - name: shared-volume
            mountPath: /kazi_PV_dir
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: pvc-for-k8-container-app