apiVersion: v1
kind: Service
metadata:
  name: container-2-service
spec:
  type: LoadBalancer
  selector:
    app: k8-container-app-2
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000